apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vpa-auto
spec:
  targetRef:
    apiVersion: "apps.openshift.io/v1"
    kind:       DeploymentConfig
    name:       simple-webpage
  updatePolicy:
    updateMode: "Auto"
