apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-prom-creds
  namespace: my-project
spec:
  secretTargetRef:
  - parameter: bearerToken
    name: thanos-bt-secret     ### <--- update this token to your own
    key: bearerToken

